# No.1

<img src= 'Screen Shot 2022-06-21 at 18.06.46.png'>

In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
Tensor_4D = np.array([
    [[[23, 50],
    [7, 12]],
    [[57,67],
    [99,43]]],
    [[[75, 21],
    [57, 12]],
    [[87,26],
    [18,84]]]
])

print(Tensor_4D)
print(Tensor_4D.ndim)
print(Tensor_4D.shape) #kalo dimensinya 4D shape nya (jml3D, jml2D, jml1D, jmldidalam1D)

[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]
4
(2, 2, 2, 2)


# No.2

<img src='Screen Shot 2022-06-21 at 18.26.34.png'>

disini A adalah matrix 3x3, sedangkan B (harusnya b kecil) adalah vektor 3x1. Karenanya bisa dilakukan perkalian (di matriks perkalian itu maksudnya dot product), sedangkan perkalian antar elemen dinamakan hadamard product.

In [18]:
A = np.array([
    [23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]
])

b = np.array(
    [17,22,19]
)

A@b

array([1852, 2454, 4305])

# No.3

<img src= 'Screen Shot 2022-06-21 at 18.41.29.png'>

In [21]:
A.transpose()

#atau

A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [23]:
det_A = np.linalg.det(A)
det_A

131344.0000000002

cari determinan buat matriks 2x2

In [26]:
a = np.array([
    [2,1],
    [3,1]
])

det_a = np.linalg.det(a)
det_a

-1.0000000000000002

In [27]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

Cari determinan buat matriks 2x2

<img src= 'Screen Shot 2022-06-21 at 19.12.58.png' weight=200 height=200>

In [28]:
np.linalg.inv(a)

array([[-1.,  1.],
       [ 3., -2.]])

### Matriks singular--> tidak ada inverse karena determinannya 0 (per baris merupakan kelipatannya, misalkan di bawah ini baris 2 merupakan kelipatan 3 baris 1)

In [29]:
C = np.array([
    [1,2],
    [3,6]
])

np.linalg.inv(C)

LinAlgError: Singular matrix