# NGC 6

<img src = 'Screen Shot 2022-06-22 at 21.58.29.png'>

In [2]:
import sympy as sy

In [3]:
x = sy.Symbol('x')

#kalo mau x nya terdefinisi sebagai variabel harus di sy.Symbol dlu, kalo nggak error

In [3]:
y = x**2 + 2*x +1
y


x**2 + 2*x + 1

Kalo mau cari turunan pertama (sebenernya harusnya d(y)/d(x), notasi dy biar mempersimpel aja):

In [5]:
dy = y.diff()
dy

2*x + 2

Misalkan aja mau cari diferensial kedua

In [6]:
d2y = y.diff().diff()
d2y

2

Lanjut ke soal selanjutnya, y ganti ke z

In [7]:
z = 4*x**3 - 3*x**2 + 2*x -1
z

4*x**3 - 3*x**2 + 2*x - 1

cara kedua buat diferensial, pake sy

In [8]:
dz = sy.diff(z)

In [9]:
dz

12*x**2 - 6*x + 2

# NGC 7 

In [4]:
a = -3/4*x + 5/4
a

1.25 - 0.75*x

function dalam mencari gradien

In [6]:
m = sy.tensor.array.derive_by_array(a, x)
m

-0.750000000000000

Atau import dlu functionnya

In [13]:
from sympy.tensor.array import derive_by_array

m = derive_by_array(a, x)
m

-0.750000000000000

atau dengan cara lain kalo mau pake numpy

In [7]:
import numpy as np

In [12]:
x = np.array([1,2])
y = -3/4*x + 5/4

In [13]:
np.gradient(y,x)

array([-0.75, -0.75])

# NGC 8

<img src = 'Screen Shot 2022-06-22 at 22.38.32.png'>

In [16]:
fx = 3*x**2 - 6*x + 3
fx

3*x**2 - 6*x + 3

In [17]:
fx.integrate()

x**3 - 3*x**2 + 3*x

In [19]:
fxdx = sy.integrate(fx)
fxdx

x**3 - 3*x**2 + 3*x

Soal selanjutnya

In [20]:
fx_2 = 8*x**3 - x**2 + 5*x - 1
fx_2

8*x**3 - x**2 + 5*x - 1

In [22]:
fx_2.integrate()

2*x**4 - x**3/3 + 5*x**2/2 - x

# Sedikit tentang algoritma google kemarin

resource: https://www.youtube.com/watch?v=qxEkY8OScYY&list=PL6kUUS3GdUpFVkif5-k4iGLJTFV2YSf9f&index=3

In [23]:
import numpy as np

In [24]:
matrix = np.array([
    [0,0,1/2,1/2],
    [1,0, 0, 1/2],
    [0, 1/2, 0, 0],
    [0, 1/2,1/2,0]
])

susp_eigen_vec = np.array([0.217, 0.348, 0.174, 0.261])

In [25]:
eig_val, eig_vec = np.linalg.eig(matrix)

In [28]:
eig_val

array([ 1.        +0.j        , -0.39246007+0.65357064j,
       -0.39246007-0.65357064j, -0.21507985+0.j        ])

In [29]:
eig_vec

array([[ 0.42107596+0.j        , -0.08038366+0.48852922j,
        -0.08038366-0.48852922j, -0.40293793+0.j        ],
       [ 0.67372154+0.j        ,  0.65586562+0.j        ,
         0.65586562-0.j        ,  0.22961027+0.j        ],
       [ 0.33686077+0.j        , -0.22144714-0.3687798j ,
        -0.22144714+0.3687798j , -0.53377912+0.j        ],
       [ 0.50529115+0.j        , -0.35403483-0.11974942j,
        -0.35403483+0.11974942j,  0.70710678+0.j        ]])

In [30]:
biggest_val = np.argmax(eig_val)
biggest_val

0

In [31]:
vec_unit =  susp_eigen_vec/np.linalg.norm(susp_eigen_vec)
vec_unit

array([0.42027911, 0.673996  , 0.336998  , 0.505497  ])